# Check ASP trends

In [9]:
# Import Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [10]:
data2025=pd.read_csv('2025.csv',encoding='utf-8')
data2026=pd.read_csv('2026PartYear.csv',encoding='utf-8')

In [11]:
data2025.columns
data2026.columns

Index(['Report', 'Timeframe', 'Period', 'Type', 'Geography',
       'Current Year Week Ending', 'ASP Current Year', 'Total Bulk and Bags',
       '4046', '4225', '4770', 'TotalBagged', 'Sml Bagged', 'Lrg Bagged',
       'X-Lrg Bagged', 'Unknown Bag Size'],
      dtype='str')

In [12]:
data2025['year']=2025
data2026['year']=2026

In [20]:
asp_2025=data2025.groupby('Geography')['ASP Current Year'].mean()
asp_2026=data2026.groupby('Geography')['ASP Current Year'].mean()

asp_compare = pd.DataFrame({"ASP_2025": asp_2025,"ASP_2026": asp_2026})
asp_compare["YOY_%_Change"] = ((asp_compare["ASP_2026"]-asp_compare["ASP_2025"]) / asp_compare["ASP_2025"]*100)

asp_compare

                          ASP_2025  ASP_2026  YOY_%_Change
Geography
5 Boroughs/New York City  1.379945  1.287725     -6.682904
Albany                    1.277062  1.148968    -10.030352
Atlanta                   1.415546  1.217641    -13.980806
Baltimore/Washington      1.266300  1.212794     -4.225354
Birmingham/Montgomery     1.236922  1.119331     -9.506688
...                            ...       ...           ...
Toledo                    1.452876  1.350914     -7.017982
Total U.S.                1.417314  1.274379    -10.084912
West                      1.696126  1.473910    -13.101399
West Tex/New Mexico       1.329347  1.205748     -9.297723
Wichita                   1.258723  1.124806    -10.639149

[64 rows x 3 columns]

In [22]:
vol_2025 = data2025.groupby("Geography")["Total Bulk and Bags"].sum()
vol_2026 = data2026.groupby("Geography")["Total Bulk and Bags"].sum()

vol_compare = pd.DataFrame({"Volume_2025": vol_2025,"Volume_2026": vol_2026})
vol_compare["YOY_%_Change"]=((vol_compare["Volume_2026"]-vol_compare["Volume_2025"])/vol_compare["Volume_2025"] * 100)

vol_compare

                           Volume_2025   Volume_2026  YOY_%_Change
Geography
5 Boroughs/New York City  4.381567e+07  3.040420e+07    -30.608854
Albany                    8.639695e+06  5.881607e+06    -31.923435
Atlanta                   5.640996e+07  4.167280e+07    -26.125102
Baltimore/Washington      9.663643e+07  7.088344e+07    -26.649361
Birmingham/Montgomery     2.384717e+07  1.774771e+07    -25.577283
...                                ...           ...           ...
Toledo                    9.139971e+06  6.594763e+06    -27.847004
Total U.S.                2.986017e+09  2.125800e+09    -28.808180
West                      4.591716e+08  3.117290e+08    -32.110550
West Tex/New Mexico       5.317247e+07  3.711259e+07    -30.203366
Wichita                   7.348135e+06  5.237102e+06    -28.728826

[64 rows x 3 columns]

In [23]:
plu_2025=data2025[["4046", "4225", "4770"]].sum()
plu_2026=data2026[["4046", "4225", "4770"]].sum()

plu_compare = pd.DataFrame({"PLU_2025":plu_2025,"PLU_2026":plu_2026})

plu_compare["Share_2025_%"]=(plu_compare["PLU_2025"]/plu_compare["PLU_2025"].sum())*100
plu_compare["Share_2026_%"]=(plu_compare["PLU_2026"]/plu_compare["PLU_2026"].sum())*100

plu_compare

          PLU_2025      PLU_2026  Share_2025_%  Share_2026_%
4046  3.611733e+09  2.390150e+09     77.168791     73.021469
4225  9.474150e+08  7.441466e+08     20.242603     22.734422
4770  1.211546e+08  1.389188e+08      2.588606      4.244109